name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4
      - name: Set up uv & Python
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.10'
          enable-cache: true
      - name: Install bitfinex-api-py's dependencies
        run: uv sync
      - name: Run pre-commit hooks (see .pre-commit-config.yaml)
        uses: pre-commit/action@v3.0.1
      - name: Run mypy to ensure correct type hinting
        run: uv run mypy bfxapi
